### ISSUE TITLE
Create one banner across all products to flag upcoming Start Career in BOSS Program

### ISSUE THREAD

**Issue by aassoiants** [bitcoin-dev-project/bdp-ui#32]
@adamjonas to provide banner copy
Tobi to design
@aassoiants to finalize and support copy + designs

**Products**
- [x] Bitcoin Dev Project Website
- [x] Bitcoin Search
- [x] Bitcoin TLDR
- [x] Bitcoin Transcripts
- [x] Bitcoin Transcripts Review
- [x] ChatBTC
- [x] Saving Satoshi

**Comment by adamjonas** [comment]
thinking that ₿OSS is stronger

**Comment by Emmanuel-Develops** [comment]
For design, I suggest including an option for the banner to be permanently discarded, i.e. don't show again.
Let's keep that in mind.
